#arquivo de configuracoes local/default

#configuracao de porta
server:
  port: ${SERVER_PORT}

#define qual arquivo sera rodado com base no profile
spring:
  application:
    name: "contactbook"
  config:
    activate:
      on-profile:
        - qa

  #configuracoes de banco de dados
  datasource:
    url: jdbc:postgresql://postgres-db:5432/contactBook?currentSchema=public
    username: "admin"
    password: "admin"
    driver-class-name: "org.postgresql.Driver"

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  #configuracoo do flyway
  flyway:
    locations: "db/migration"
    baseline-on-migrate: false

#configuracao swagger
springdoc:
  swagger-ui:
    path: "/contactbook/swagger-ui.html"

#endpoint viacep
viacep:
  endpoint: "viacep.com.br/ws"