#arquivo de configuracoes local/default

#configuracao de porta
server:
  port: 8090

spring:
  application:
    name: "contactbook"

#configuracoes de banco de dados
  datasource:
    url: jdbc:postgresql://localhost:15432/contactbook?currentSchema=public
    username: "admin"
    password: "admin"
    driver-class-name: "org.postgresql.Driver"
    hikari:
      schema: public

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

#configuracao do flyway
  flyway:
    locations: "db/migration"
    baseline-on-migrate: false

#configuracao swagger
springdoc:
  swagger-ui:
    path: "/contactbook/swagger-ui.html"

#endpoint viacep
viacep:
  endpoint: "viacep.com.br/ws"